version: '3.2'

services:
  node:
    image: node:10.5-alpine
    user: node
    working_dir: /srv
    volumes:
      - ./:/srv

  web:
    image: nginx:1.15-alpine
    volumes:
      - ./web/:/usr/share/nginx/html:ro
    ports:
      - 8765:80
