version: "3.2"

services:
#  traefik:
#    ports:
#      - '80:80' # Uncomment to use the 80 port on your host instead of the 8080 one.

  tools:
    volumes:
      - ~/.cache/composer:/var/www/.composer # ubuntu
      #- ~/.composer:/var/www/.composer # debian

  front:
    environment:
        DOMAIN_NAME: front.rtfm.docker

  api:
    environment:
        DOMAIN_NAME: api.rtfm.docker
