version: "3.2"

networks:
  api: ~
  front: ~

volumes:
  data-mysql: ~

services:
  traefik:
    image: traefik:v1.6-alpine
    networks:
      - api
      - front
    ports:
      - '8080:80'
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:traefik.rtfm.vcap.me'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/traefik.toml:/etc/traefik/traefik.toml

  front:
    build: docker/nginx
    volumes:
      - ./front:/srv
    depends_on:
      - front_php
    networks:
      - front
    ports:
      - '80'
    environment:
      - PHP_BACKEND=front_php:9001
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:front.rtfm.vcap.me'

  front_php:
    build: docker/php-fpm
    volumes:
      - ./front:/srv
    environment:
      - APP_ENV=dev
    networks:
      - front
      - api

  api:
    build: docker/nginx
    volumes:
      - ./api:/srv
    depends_on:
      - api_php
    networks:
      - api
    ports:
      - '80'
    environment:
      - PHP_BACKEND=api_php:9001
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:api.rtfm.vcap.me'

  api_php:
    build: docker/php-fpm
    volumes:
      - ./api:/srv
    environment:
      - APP_ENV=dev
    networks:
      - api

#  mysql:
#    image: mysql:5.7
#    networks:
#      - api
#    environment:
#      - MYSQL_RANDOM_ROOT_PASSWORD=1
#      - MYSQL_DATABASE=api
#      - MYSQL_USER=api
#      - MYSQL_PASSWORD=apipasswd
#    volumes:
#      - data-mysql:/var/lib/mysql/

  tools:
    build: docker/tools
    command: sleep 999999d
    volumes:
      - ./api:/srv/api
      - ./front:/srv/front
    environment:
      - APP_ENV=dev
    networks:
      - api
      - front
